CREATE DATABASE IF NOT EXISTS rpc_auth;
CREATE DATABASE IF NOT EXISTS rpc_spreadsheet;
CREATE DATABASE IF NOT EXISTS rpc_spreadsheet_0;
CREATE DATABASE IF NOT EXISTS rpc_spreadsheet_1;
CREATE DATABASE IF NOT EXISTS rpc_file;
CREATE DATABASE IF NOT EXISTS rpc_file_0;
CREATE DATABASE IF NOT EXISTS rpc_file_1;
