services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: ${DOCKER_USER:-http-rpc}/nginx-frontend:latest
    volumes: !override
      - ./deploy/nginx/nginx.frontend.conf:/etc/nginx/nginx.conf:ro
      - nginx_certs:/certs

volumes:
  nginx_certs:
    driver: local
