FROM nginx:1.27
RUN apt-get update && apt-get install -y openssl apache2-utils curl && \
    mkdir -p /certs && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
      -keyout /certs/server.key -out /certs/server.crt \
      -subj "/CN=luochuanbaiRPC" && \
    rm -rf /var/lib/apt/lists/*
