FROM golang:1.24-alpine
ENV GOPROXY=https://goproxy.cn,direct
RUN apk add --no-cache git protobuf-dev protoc
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.1
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.4.0
RUN go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.26.3
WORKDIR /build
COPY rpc_auth.proto .
COPY google/ ./google/
RUN protoc -I . --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative --grpc-gateway_out=. --grpc-gateway_opt=paths=source_relative rpc_auth.proto
CMD echo ok
