apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: http-rpc

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - mysql/auth-statefulset.yaml
  - mysql/spreadsheet-statefulset.yaml
  - mysql/file-statefulset.yaml
  - redis/cluster-statefulset.yaml
  - minio/statefulset.yaml
  - auth/deployment.yaml
  - auth/service.yaml
  - sheet/deployment.yaml
  - sheet/service.yaml
  - file/deployment.yaml
  - file/service.yaml
  - gateway/deployment.yaml
  - gateway/hpa.yaml
  - ingress/ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: http-rpc

images:
  - name: http-rpc/server
    newTag: latest
  - name: http-rpc/gateway
    newTag: latest
