port ${REDIS_PORT}
bind 0.0.0.0
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
appendonly yes
appendfsync everysec
requirepass ${REDIS_PASSWORD}
masterauth ${REDIS_PASSWORD}
